

tasks:
  - init: |
      export EDITOR="command gp open -w" VISUAL="command gp open -w"
      cp -f /workspace/ohmyzsh/templates/zshrc.zsh-template ~/.zshrc
      ln -sf /workspace/ohmyzsh ~/.oh-my-zsh
      
    command: |
      exec zsh
      npm install -g pnpm
  - before: printf "\n[settings]\napi_key = $WAKA_TIME_API_KEY\n" > ~/.wakatime.cfg
